server:
  port: 9001

  undertow:
    buffer-size: 1024
    direct-buffers: true
    tomcat:
      max-threads: 1000
      max-connections: 20000
      min-spare-threads: 20
      accept-count: 700
    threads:
      io: 16
      worker: 400

spring:
  aop:
    proxy-target-class: true
    autoconfigure:
      exclude4: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    datasource-name: gaussdb
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: *****
        loginPassword: *****
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid:
        initial-size: 10
        min-idle: 10
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  #redis
  redis:
    database: 1
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379
  #mybatis plus
  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
      banner: false
      db-config:
        id-type: ASSIGN_ID
        table-underline: true
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      call-setters-on-nulls: true

  #Mybatis 日志
  logging:
    level:
      com.zgt.healthode.mapper: info

gitee:
  client:
    cid: ******
    secret: ******
  redirect:
    uri: http://myurl.com


opengauss:
  common:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=practice
    username: user
    password: pass
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    datasource-name: practice

  super:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    datasource-name: superpractice
    docker-image: enmotech/opengauss:latest


docker:
  url: tcp://localhost:2375
